site_name: Notas musicais
repo_url: https://github.com/koanjazz/notas-musicais
repo_name: koanjazz/Notas-musicais
edit_uri: tree/master/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo1.jpg
  favicon: assets/logo1.jpg

markdown_extensions: 
  - attr_list

extra_css:
  - stylesheets/extra.css




